// <auto-generated />
using System;
using Dotnet7OnionArchitecture.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet7OnionArchitecture.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250123192441_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("Dotnet7OnionArchitecture.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 666, DateTimeKind.Local).AddTicks(7912),
                            IsDeleted = false,
                            Name = "Çetiner - Yalçın"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 666, DateTimeKind.Local).AddTicks(8037),
                            IsDeleted = false,
                            Name = "Velioğlu LLC"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 666, DateTimeKind.Local).AddTicks(8153),
                            IsDeleted = false,
                            Name = "Numanoğlu, Ekici and Tahincioğlu"
                        });
                });

            modelBuilder.Entity("Dotnet7OnionArchitecture.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 667, DateTimeKind.Local).AddTicks(62),
                            IsDeleted = false,
                            Name = "Elektronik",
                            ParentId = 0,
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 667, DateTimeKind.Local).AddTicks(64),
                            IsDeleted = false,
                            Name = "Moda",
                            ParentId = 0,
                            Priority = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 667, DateTimeKind.Local).AddTicks(65),
                            IsDeleted = false,
                            Name = "Bilgisayar",
                            ParentId = 1,
                            Priority = 3
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 667, DateTimeKind.Local).AddTicks(67),
                            IsDeleted = false,
                            Name = "Kadın",
                            ParentId = 2,
                            Priority = 4
                        });
                });

            modelBuilder.Entity("Dotnet7OnionArchitecture.Domain.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 668, DateTimeKind.Local).AddTicks(4875),
                            Description = "Quis quam karşıdakine enim ad.",
                            IsDeleted = false,
                            Title = "Sıla."
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 668, DateTimeKind.Local).AddTicks(4905),
                            Description = "Kalemi teldeki sandalye ad koşuyorlar suscipit numquam.",
                            IsDeleted = true,
                            Title = "Makinesi dolore."
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 668, DateTimeKind.Local).AddTicks(4961),
                            Description = "Adanaya sed sed cezbelendi qui.",
                            IsDeleted = false,
                            Title = "Consequuntur."
                        });
                });

            modelBuilder.Entity("Dotnet7OnionArchitecture.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 669, DateTimeKind.Local).AddTicks(7383),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Discount = 2.495202544793998m,
                            IsDeleted = false,
                            Price = 138.40m,
                            Title = "Awesome Steel Chicken"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 669, DateTimeKind.Local).AddTicks(7405),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Discount = 1.1999694528651457m,
                            IsDeleted = false,
                            Price = 189.52m,
                            Title = "Gorgeous Frozen Hat"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CreateDate = new DateTime(2025, 1, 23, 22, 24, 41, 669, DateTimeKind.Local).AddTicks(7422),
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Discount = 7.145818180266187m,
                            IsDeleted = false,
                            Price = 917.82m,
                            Title = "Generic Frozen Gloves"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("Dotnet7OnionArchitecture.Domain.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dotnet7OnionArchitecture.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dotnet7OnionArchitecture.Domain.Entities.Detail", b =>
                {
                    b.HasOne("Dotnet7OnionArchitecture.Domain.Entities.Category", "Category")
                        .WithMany("Details")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Dotnet7OnionArchitecture.Domain.Entities.Product", b =>
                {
                    b.HasOne("Dotnet7OnionArchitecture.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Dotnet7OnionArchitecture.Domain.Entities.Category", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
